### ISSUE TITLE
Look at mathplotlib show mechanism

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vivid#100]
Take a look at how other libs show their plots, and interactive ones. (HTML? or what?)
how does it look in ipython, how does it look at pycharm?

DOD - Description of the show mechanism of matplotlib in the comments section of this issue.
Specifically answer the ipython and pycharm solutions. 
Later have a discussion with Tomer

**Comment by raphae2118** [comment]
#### Matplotlib's show mechanism
To support large variations of output formats (GUIs, Image files, Web-based) matplotlib uses multiple "backends" (backends [list](https://matplotlib.org/3.3.1/api/index_backend_api.html)). But, it seems like most platforms already have their own backend (this I found out after our phone call). I'll be covering the ones that I think of to be related.

- [template](https://matplotlib.org/3.3.1/api/backend_template_api.html) "A fully functional, do-nothing backend intended as a template for backend writers" maybe we can consider our own backend idk.
- [ipykernel's backend_inline](https://github.com/ipython/ipykernel/blob/master/ipykernel/pylab/backend_inline.py) This one isn't in matplotlib but is based on their [agg backend](https://matplotlib.org/3.3.1/api/backend_agg_api.html), it's a backend that exists in the ipykernel in pylab and gets switched to when `%matplotlib inline` is executed. It uses the [ipython.display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html) module (might be better than iframe if done correctly)
- [jetbrain's backend interagg](https://github.com/JetBrains/intellij-community/blob/master/python/helpers/pycharm_matplotlib_backend/backend_interagg.py) This one is also based on matplotlib's [agg backend](https://matplotlib.org/3.3.1/api/backend_agg_api.html) seems like a lot of it's code is copied from pyplot excluding some pycharm displaying mechanism.

Regarding the way in which matplotlib is choosing a backend. Pycharm and jupyter have their own backend so I assume its related to the enviroment but I think it probably just defaults to the agg backend (the agg backend is a backend that works with the agg cpp library that is used to render plots).
