### ISSUE TITLE
Display a model in jupyter notebook

### ISSUE THREAD

**Issue by raphae2118** [GalaxyHunters/Vivid#104]
I'm gonna try using ipython's Iframe and model-viewer
DoD: A cell output that contains an interactive render of the model

**Comment by tussbaum** [comment]
Take a look at this webpage: https://github.com/KhronosGroup/glTF
search for: "Sample models"

**Comment by raphae2118** [comment]
Ended up using the trimesh python package it worked smoothly after the web approach yielded some security bugs of some sort, moving this to "in review" adding an issue to cover trimesh more deeply.
