### ISSUE TITLE
Particle Position Scale

### ISSUE THREAD

**Issue by Beilinson** [GalaxyHunters/Vivid#139]
Explanation: Simulations on a large enough scale get some memory leak error and do not work.
Example: Supernova (Scale from -1e10 to 1e10 (20,000,000,000 units apart at farthest points).
Temp Fix: Scale down by dividing until realistic scale (at what scale does this start becoming an issue?)

**Comment by tussbaum** [comment]
I know why like this. so talk to me first

**Comment by tussbaum** [comment]
We should check it in the Elad new code
