### ISSUE TITLE
2_Assimp Design

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vivid#194]
DOD - 4 function encapsulation Assimp
import model, export model
import animation, export animation

a = animation()
a.export(<filetype>, <FilePath> or <Stream>)
* Think about the standard export implementation in CPP and PY.

**Comment by lazy-fox304** [comment]
Didn't you already do it?
With the file anf function writing, I only have the implementation left to do (even though I disagree with some of the design, perhaps we should discuss later).

**Comment by tussbaum** [comment]
Humm, I made only the interface from the vivid side.
I guess we should discuss how to do it, with better knowledge of the scene's internal structure.
Anyway, if you disagree, it's better we would talk about it. it was mostly an outline.
