### ISSUE TITLE
check conversions methods and results

### ISSUE THREAD

**Issue by raphae2118** [GalaxyHunters/Vivid#99]
Formats to be checked in order to integrate in <model-viewer>:
obj <-> glb 
fbx <-> gltf

Dod: The Pleasent feeling of a converter that is not fucking up the models and new tasks for implementing the converter in vivid.

**Comment by tussbaum** [comment]
Try finding a convertor of all 3D format to the .gltf file format, as they say: 
"One format to rule them all, 
one format to find them,
one format to bring them all and in the darkness bind them!"

Rephrase the DOD: 
- Shape and colors and alpha do not change through the conversion, nor the file size.
- Lines do not change
- Animation does not change, not by time, camera or file size.
in case of file size change, tell Tomer
